---
- hosts: localhost
  connection: local
  tasks:
    - name: Create & Start Container
      docker_container:
      name: myweb
      image: "jihoon1008/myweb:latest"
      state: started
      ports:
        - "80:8080"
